dist: bionic
os: linux
language: python
python:
  - "3.7"

env:
  global:
    - CACHE_IMAGE=voteamerica/turnout-ci-cache

jobs:
  include:
    - stage: build
      before_install:
      - touch .env
      - docker pull $CACHE_IMAGE:latest || true

      script:
        - docker-compose build

      after_success:
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        - docker push $CACHE_IMAGE:latest

    - stage: test
      env:
        - TEST_GROUP=1
        - TEST_GROUP=2

      before_install:
      - touch .env
      - docker pull $CACHE_IMAGE:latest || true

      install:
        - docker-compose build

      before_script:
        - docker-compose up -d

      script:
        - docker-compose exec server pytest -n auto --test-group-count 2 --test-group=$TEST_GROUP /app/
        - docker-compose exec server mypy /app/

      after_success:
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        - docker push $CACHE_IMAGE:latest

    - stage: deploy
      script: /bin/true

      deploy:
        - provider: script
          script: bash scripts/travis_deploy_tags.sh
          on:
            tags: true
            all_branches: true
            repo: vote/turnout

        - provider: script
          script: bash scripts/travis_deploy_master.sh
          on:
            branch: master
            repo: vote/turnout
